import streamlit as st


def draw_muesli_landingpage():
    st.title('Muesli Practice Helper')
    st.header('Start a New Recording Session')
    st.button('Start a New Session', key="should_create_new_session")
    st.title('OR')
    draw_session_connection_section()


def draw_session_connection_section():
    st.header('Attach to Another Session')
    st.text_input('Enter the six-digit ID generated by the other session:', key='last_access_token_tried')

    user_access_token_id = st.session_state.get('last_access_token_tried', None)
    # Print nothing if no session is specified
    if user_access_token_id:
        st.error(f'Token "{user_access_token_id}" has expired, has already been used, or never existed in the first place')


